services:
  - type: web
    name: conversor-pdf
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn conversor_pdf.wsgi:application"
    envVars:
      - key: SECRET_KEY
        value: sua-chave-super-secreta
      - key: DEBUG
        value: False
